# Generated by Django 4.1.7 on 2023-03-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('avg_price', models.FloatField()),
                ('gen_reputuation', models.CharField(max_length=500)),
                ('graduation_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GradStudent',
            fields=[
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('DOB', models.DateField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('career', models.CharField(max_length=50)),
                ('employability', models.FloatField()),
                ('emp_options', models.IntegerField()),
                ('travel_opps', models.FloatField()),
                ('avg_carrer_length', models.IntegerField()),
            ],
        ),
    ]
