# Generated by Django 4.1.7 on 2023-03-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradstudent',
            name='gender',
            field=models.CharField(default='male', max_length=50),
        ),
    ]
