# Generated by Django 4.1.7 on 2023-03-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCApp', '0004_career_remove_studyprogram_avg_carrer_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyprogram',
            name='career',
        ),
        migrations.AddField(
            model_name='college',
            name='total_programs',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='college',
            name='gen_reputuation',
            field=models.CharField(choices=[(1, 'First Class'), (2, 'Second Class'), (3, 'Third Class'), (4, 'Mediocre')], default=1, max_length=500),
        ),
    ]
