# Generated by Django 4.1.7 on 2023-03-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCApp', '0005_remove_studyprogram_career_college_total_programs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyprogram',
            name='career',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
