# Generated by Django 4.1.7 on 2023-03-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCApp', '0006_studyprogram_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogram',
            name='career',
            field=models.CharField(max_length=50),
        ),
    ]
