# Generated by Django 4.1.7 on 2023-03-27 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CCApp', '0007_alter_studyprogram_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogram',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CCApp.career'),
        ),
    ]
