# Generated by Django 4.1.7 on 2023-03-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCApp', '0008_alter_studyprogram_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='Campus_type',
            field=models.CharField(choices=[(1, 'Closed campus with student housing'), (2, 'Open campus with student housing'), (3, 'Open campus without student housing'), (4, 'Closed campus without student housing')], default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='college',
            name='security_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='total_clubs',
            field=models.IntegerField(default=0),
        ),
    ]
