# Generated by Django 4.1.7 on 2023-03-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCApp', '0009_college_campus_type_college_security_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='graduation_rate',
        ),
    ]
