# Generated by Django 4.1.7 on 2023-04-03 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CCApp', '0010_remove_college_graduation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradstudent',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gradstudent',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
